### ISSUE TITLE
One more MPRestError 

### ISSUE THREAD

**Issue by similt** [kumagai-group/pydefect#10]
When I execute the below command : 
pydefect_util cefm -a atom_energies.yaml -e Mg Al O

I am getting: 

   INFO: -- Settings from vise.yaml:
   INFO:
   INFO: -- Settings from pydefect.yaml:
   INFO:
Traceback (most recent call last):
  File "/home/user/Downloads/anaconda3/bin/pydefect_util", line 8, in <module>
    sys.exit(main())
  File "/home/user/Downloads/anaconda3/lib/python3.9/site-packages/pydefect/cli/main_util.py", line 133, in main
    args.func(args)
  File "/home/user/Downloads/anaconda3/lib/python3.9/site-packages/pydefect/cli/main_util_functions.py", line 24, in composition_energies_from_mp
    composition_energies = make_composition_energies_from_mp(
  File "/home/user/Downloads/anaconda3/lib/python3.9/site-packages/pydefect/cli/vasp/make_composition_energies_from_mp.py", line 28, in make_composition_energies_from_mp
    entries: List[ComputedEntry] = MpEntries(elements).materials
  File "/home/user/Downloads/anaconda3/lib/python3.9/site-packages/pydefect/util/mp_tools.py", line 55, in __init__
    self.materials = m.get_entries(
  File "/home/user/Downloads/anaconda3/lib/python3.9/site-packages/mp_api/client/mprester.py", line 518, in get_entries
    docs = self.thermo.search(
  File "/home/user/Downloads/anaconda3/lib/python3.9/site-packages/mp_api/client/routes/thermo.py", line 136, in search
    return super()._search(
  File "/home/user/Downloads/anaconda3/lib/python3.9/site-packages/mp_api/client/core/client.py", line 956, in _search
    return self._get_all_documents(
  File "/home/user/Downloads/anaconda3/lib/python3.9/site-packages/mp_api/client/core/client.py", line 1005, in _get_all_documents
  File "/home/user/Downloads/anaconda3/lib/python3.9/site-packages/mp_api/client/core/client.py", line 1005, in _get_all_documents
    results = self._query_resource(
  File "/home/user/Downloads/anaconda3/lib/python3.9/site-packages/mp_api/client/core/client.py", line 294, in _query_resource
    data = self._submit_requests(
  File "/home/user/Downloads/anaconda3/lib/python3.9/site-packages/mp_api/client/core/client.py", line 440, in _submit_requests
    initial_data_tuples = self._multi_thread(
  File "/home/user/Downloads/anaconda3/lib/python3.9/site-packages/mp_api/client/core/client.py", line 661, in _multi_thread
    data, subtotal = future.result()
  File "/home/user/Downloads/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/user/Downloads/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/user/Downloads/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/Downloads/anaconda3/lib/python3.9/site-packages/mp_api/client/core/client.py", line 763, in _submit_request_and_process
    raise MPRestError(
mp_api.client.core.client.MPRestError: REST query returned with error status code 400 on URL https://api.materialsproject.org/thermo/?_fields=entries&formula=e_above_hull&_limit=500 with message:
Problem processing one or more provided formulas.

**Comment by yuuukuma** [comment]
Sorry, now "pydefect_util cefm" is not supported, so I will remove it in the near future.

**Comment by similt** [comment]
@yuuukuma Could you tell me how to generate phase diagram,  when MgAl2O4 is doped with element X and
pydefect_vasp mp -e Mg Al O X --e_above_hull 0.0005
does not create any composition of X?  (My aim is to calculate chemical potential when Mg is replaced with X)

**Comment by yuuukuma** [comment]
It sounds strange. When using the old Materials Project api key, 
pydefect_vasp mp -e Mg Al O Ca  --e_above_hull 0.0005
generates these directories.
Al2O3_mp-1143/         Ca4MgAl3_mp-640340/   CaAl2_mp-2404/       CaMg2_mp-2432/    Ca_mp-1183484/       Mg17Al12_mp-2151/  MgO_mp-1265/    mol_O2/
Al_mp-134/             Ca6Al7O16_mp-721592/  CaAl4O7_mp-4867/     CaMg_mp-1039148/  Ca_mp-132/           MgAl2O4_mp-3536/   Mg_mp-1094122/
Ca11Al14O32_mp-33318/  Ca8Al3_mp-1190736/    CaMg149_mp-1184449/  CaO_mp-2605/      Mg149Al_mp-1185596/  MgAl2_mp-1094116/

Could you let me know which directories are generated?

**Comment by yuuukuma** [comment]
I also tried new MP api, and found the following directories including Ca compounds.
Al11O18_mp-1229215/   Ca4MgAl3_mp-640340/   CaAl4O7_mp-4867/      CaO2_mp-634859/       Mg17Al12_mp-2151/     Mg_mp-1056702/
Al2O3_mp-1143/        Ca6Al7O16_mp-721592/  CaMg149_mp-1184449/   CaO_mp-2605/          MgAl2O4_mp-3536/      mol_O2/
Al_mp-134/            Ca8Al3_mp-1190736/    CaMg2_mp-2432/        Ca_mp-45/             MgAl2_mp-1094116/
Ca11Al14O32_mp-33318/ CaAl2_mp-2404/        CaMg_mp-1039148/      Mg149Al_mp-1185596/   MgO_mp-1265/

**Comment by similt** [comment]
I was trying 
pydefect_vasp mp -e Rb In Cl Cu --e_above_hull 0.0005
Initiallay there were no folders. But now rerunning the above command gives enough compounds!
