### ISSUE TITLE
NoIonicConvError from converged geometry optimizations 

### ISSUE THREAD

**Issue by similt** [kumagai-group/pydefect#12]
When I am calculating energy corrections for various defects as 
pydefect efnv -d *_*/ -pcr perfect/calc_results.json -u ../unitcell/unitcell.yaml
But I am getting error: NoIonicConvError
I checked and found that geometry is converged.  Is there any way to get rid of this error? 

   INFO: -- Settings from vise.yaml:
   INFO:
   INFO: -- Settings from pydefect.yaml:
   INFO:
   INFO: Parsing data in Sn_Cl1_0 ...
WARNING: Ionic convergence in Sn_Cl1_0 is not reached.
Traceback (most recent call last):
  File "/project/ktemp/anaconda3/lib/python3.9/site-packages/pydefect/cli/main_tools.py", line 54, in parse_dirs
    _return = _inner_function(_dir)
  File "/project/ktemp/anaconda3/lib/python3.9/site-packages/pydefect/cli/main_functions.py", line 183, in _inner
    calc_results = get_calc_results(_dir, args.check_calc_results)
  File "/project/ktemp/anaconda3/lib/python3.9/site-packages/pydefect/cli/main_functions.py", line 49, in get_calc_results
    raise NoIonicConvError
pydefect.analyzer.calc_results.NoIonicConvError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/ktemp/anaconda3/bin/pydefect", line 8, in <module>
    sys.exit(main())
  File "/project/ktemp/anaconda3/lib/python3.9/site-packages/pydefect/cli/main.py", line 343, in main
    args.func(args)
  File "/project/ktemp/anaconda3/lib/python3.9/site-packages/pydefect/cli/main_functions.py", line 198, in make_efnv_correction_main_func
    parse_dirs(args.dirs, _inner, args.verbose, file_name)
  File "/project/ktemp/anaconda3/lib/python3.9/site-packages/pydefect/cli/main_tools.py", line 61, in parse_dirs
    print(e.args[1])
IndexError: tuple index out of range

**Comment by yuuukuma** [comment]
If the calculation is converged for sure, I don't know the reason.
Could you rerun the calculation from the converged CONTCAR file and run the same command again?

**Comment by similt** [comment]
rerunning the calculation solved the error!
