### ISSUE TITLE
A bug in Calculation of competing phases

### ISSUE THREAD

**Issue by XuefeiYan1995** [kumagai-group/pydefect#13]
Dear Developers,

Thank you for taking time out of your busy schedule to read my issue. 
Recently, I had a problem with using Pydefect to calculate point defects.

Following the guidelines, I type the code "**pydefect_vasp mp -e Mg Al O --e_above_hull 0.0005**" to calculate competing phases.
However, I did not get the results I expected. The error is shown as follows:

-------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ * /Soft/Anaconda3/bin/pydefect_vasp", line 5, in <module>
    from pydefect.cli.vasp.main_vasp import main
  File "/home/ * /Soft/Anaconda3/lib/python3.8/site-packages/pydefect/cli/vasp/main_vasp.py", line 10, in <module>
    from pydefect.cli.main import epilog, description, add_sub_parser, dirs_parsers
  File "/home/ * /Soft/Anaconda3/lib/python3.8/site-packages/pydefect/cli/main.py", line 13, in <module>
    from pydefect.cli.main_functions import plot_defect_energy, \
  File "/home/ * /Soft/Anaconda3/lib/python3.8/site-packages/pydefect/cli/main_functions.py", line 10, in <module>
    from pydefect.analyzer.defect_energy_plotter import DefectEnergyMplPlotter
  File "/home/ * /Soft/Anaconda3/lib/python3.8/site-packages/pydefect/analyzer/defect_energy_plotter.py", line 8, in <module>
    from labellines import labelLines
  File "/home/ * /Soft/Anaconda3/lib/python3.8/site-packages/labellines/__init__.py", line 1, in <module>
    from .core import labelLine, labelLines
  File "/home/ * /Soft/Anaconda3/lib/python3.8/site-packages/labellines/core.py", line 9, in <module>
    from .line_label import LineLabel
  File "/home/ * /Soft/Anaconda3/lib/python3.8/site-packages/labellines/line_label.py", line 9, in <module>
    from .utils import normalize_xydata
  File "/home/ * /Soft/Anaconda3/lib/python3.8/site-packages/labellines/utils.py", line 8, in <module>
    def normalize_xydata(line: Line2D) -> tuple[np.ndarray, np.ndarray]:
**TypeError: 'type' object is not subscriptable**

----------------------------------------------------------------------------------------------------------------
I am sure I successfully installed pydefect. And the error looks like a bug. 
Could you help me solve the problem?

I am looking forward to hearing your reply soon. Thank you very much!

Best regards,
 
Xuefei Yan

**Comment by yuuukuma** [comment]
Thanks for your post.
The error is attributed to labellines package.
Could you let me know the version of labellines, and if it is 0.5.2, could you change the version of to 0.5.1?

**Comment by XuefeiYan1995** [comment]
> 

Thank you very much for your reply.

The labellines package I use is version 0.5.2.
Now I want to change to version 0.5.1, but I don't know where to download it. 
Is it convenient to provide an installation package or link?

My email is yxf0125@aliyun.com

Best regards,
Xuefei Yan

**Comment by yuuukuma** [comment]
You can change the version using 
pip install labellines==0.5.1
Anyway, this is not the problem of pydefect, please solve it by yourself.

**Comment by XuefeiYan1995** [comment]
> You can change the version using pip install labellines==0.5.1 Anyway, this is not the problem of pydefect, please solve it by yourself.

Ok, thank you very much.
