### ISSUE TITLE
Problem with add interstitial sites

### ISSUE THREAD

**Issue by wuliyanyu** [kumagai-group/pydefect#18]
Name                     Version
mp-api                     0.41.2
pydefect                   0.9.2
pymatgen                   2024.3.1
vise                         0.9.0

When I run the command

`pydefect_util ai --local_extrema ../unitcell/dos/volumetric_data_local_extrema.json -i 1 2`

I encounter the following error:

`   INFO: -- Settings from vise.yaml:
   INFO:
   INFO: -- Settings from pydefect.yaml:
   INFO:
Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/pyd/bin/pydefect_util", line 5, in <module>
    from pydefect.cli.main_util import main
  File "/home/xxx/miniconda3/envs/pyd/lib/python3.11/site-packages/pydefect/cli/main_util.py", line 11, in <module>
    from pydefect.cli.main_util_functions import make_gkfo_correction_from_vasp, \
  File "/home/xxx/miniconda3/envs/pyd/lib/python3.11/site-packages/pydefect/cli/main_util_functions.py", line 22, in <module>
    from pydefect.cli.vasp.make_composition_energies_from_mp import \
  File "/home/xxx/miniconda3/envs/pyd/lib/python3.11/site-packages/pydefect/cli/vasp/make_composition_energies_from_mp.py", line 10, in <module>
    from pydefect.util.mp_tools import MpQuery, MpEntries
ImportError: cannot import name 'MpEntries' from 'pydefect.util.mp_tools' (/home/xxx/miniconda3/envs/pyd/lib/python3.11/site-packages/pydefect/util/mp_tools.py)`

**Comment by yuuukuma** [comment]
Sorry. I tried to fix it. Could you please upgrade pydefect?

**Comment by wuliyanyu** [comment]
Thanks a lot for fixing the problem, there is no error now.
